create extension if not exists pgcrypto;

create table if not exists public.restaurants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  logo_url text,
  phone text,
  country_code text,
  currency text not null default 'SAR',
  tax_rate numeric(5,2) not null default 0 check (tax_rate >= 0 and tax_rate <= 100),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_categories_v2 (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_products_v2 (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  category_id uuid not null references public.menu_categories_v2(id) on delete restrict,
  name text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  image_url text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_options (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  product_id uuid not null references public.menu_products_v2(id) on delete cascade,
  name text not null,
  price_delta numeric(12,2) not null default 0,
  is_active boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.delivery_zones (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name text not null,
  fee numeric(12,2) not null default 0 check (fee >= 0),
  is_active boolean not null default true
);

create table if not exists public.customers_v2 (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  channel text not null check (channel in ('telegram','whatsapp','web')),
  external_user_id text,
  name text,
  phone text,
  default_address text,
  default_latitude double precision,
  default_longitude double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (restaurant_id, channel, external_user_id)
);

create table if not exists public.orders_v2 (
  id bigint generated by default as identity primary key,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  customer_id uuid references public.customers_v2(id) on delete set null,
  channel text not null check (channel in ('telegram','whatsapp','web')),
  status text not null default 'pending' check (status in ('pending','confirmed','preparing','ready','out_for_delivery','delivered','cancelled','rejected')),
  delivery_type text not null check (delivery_type in ('pickup','delivery')),
  delivery_zone_id uuid references public.delivery_zones(id) on delete set null,
  delivery_address text,
  latitude double precision,
  longitude double precision,
  payment_method text not null default 'cash',
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','failed','refunded')),
  subtotal numeric(12,2) not null check (subtotal >= 0),
  tax_amount numeric(12,2) not null default 0 check (tax_amount >= 0),
  delivery_fee numeric(12,2) not null default 0 check (delivery_fee >= 0),
  total numeric(12,2) not null check (total >= 0),
  currency text not null default 'SAR',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items_v2 (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders_v2(id) on delete cascade,
  product_id uuid references public.menu_products_v2(id) on delete set null,
  product_name text not null,
  unit_price numeric(12,2) not null,
  quantity integer not null check (quantity > 0),
  options_json jsonb not null default '[]'::jsonb,
  line_total numeric(12,2) not null
);

create index if not exists idx_categories_v2_restaurant on public.menu_categories_v2(restaurant_id, is_active, sort_order);
create index if not exists idx_products_v2_restaurant on public.menu_products_v2(restaurant_id, is_active, sort_order);
create index if not exists idx_orders_v2_restaurant_status on public.orders_v2(restaurant_id, status, created_at desc);
create index if not exists idx_customers_v2_restaurant on public.customers_v2(restaurant_id, created_at desc);

alter table public.restaurants enable row level security;
alter table public.menu_categories_v2 enable row level security;
alter table public.menu_products_v2 enable row level security;
alter table public.product_options enable row level security;
alter table public.delivery_zones enable row level security;
alter table public.customers_v2 enable row level security;
alter table public.orders_v2 enable row level security;
alter table public.order_items_v2 enable row level security;
